version: "3.8"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./files:/usr/share/nginx/html
      - uploads_data:/app/uploads
    depends_on:
      - app1
      - app2
    restart: always

  app1: &app_base
    build: ./backend
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db
    restart: always

  app2:
    <<: *app_base

  db:
    image: mysql:8.0-debian
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - goal_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always

volumes:
  goal_data:
  uploads_data:
