events {}

http {
	upstream goals_list {
		
		server app1;
		server app2;
	
	}

	include  mime.type;
	server {
		listen 80;
	
		root /usr/share/html;
		index index.html;
		try $uri $uri =404;

		location /{
			proxy_pass http://simon_game;
            		proxy_set_header Host $host;
            		proxy_set_header X-Real-IP $remote_addr;
            		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            		proxy_set_header X-Forwarded-Proto $scheme;
		}
	}

}


